FROM python:3.10-slim
RUN apt-get update -qq && apt-get install -y -qq --no-install-recommends git && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt .
RUN pip install -U pip && pip install -r requirements.txt && pip install "dvc[s3]"  # or dvc[azure]/[gcs]/[ssh]
COPY . .
ENV GIT_PYTHON_REFRESH=quiet
CMD ["bash","-lc","dvc pull -q && python -u src/model_training.py"]
