# Dockerfile.api
FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install -U pip && pip install -r requirements.txt

# copy code AFTER deps so you get layer caching
COPY src/ /app/src/

# ensure "src.api:app" is importable
ENV PYTHONPATH=/app

CMD ["uvicorn","src.api:app","--host","0.0.0.0","--port","8000","--proxy-headers","--forwarded-allow-ips","*"]
